version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    container_name: rentx
    restart: always
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/database

    volumes:
      - ./:/app
      - ./package.json:/app/package.json
      - /app/node_modules
      - api-logs:/app/logs:rw

  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentx

    volumes:
      - database-data:/var/lib/postgresql/data/


volumes:
  database-data:
  api-logs: